### ISSUE TITLE
feature request: option to send the resulting URL to a new tab and not just as GET request

### ISSUE THREAD

**Issue by peturdainn** [berrnd/send-link#1]
I was halfway writing my own extension when I noticed yours, except what I need is to send the configured URL to a new tab.
Would you accept a PR that adds this?

**Comment by berrnd** [comment]
> I need is to send the configured URL to a new tab

Not the purpose send-link, README excerpt:

> A Firefox extension to send links via customizable context-menu-entries as **_GET requests_** (MAILTO is also supported)

&nbsp;

To open a link in a new tab I would simply use Ctrl + Click or middle mouse button click...

**Comment by peturdainn** [comment]
I know how to send a link to a new tab, I need to send the URL to another server and show that output in another tab, so basically the GET request like you do, but show the response.

But nevermind, I'll fork and roll my own, thanks for your code to start from!
